### ISSUE TITLE
Error:Could not resolve all files for configuration ':ArcFaceDemo-master:debugCompileClasspath

### ISSUE THREAD

**Issue by cpq0329** [asdfqwrasdf/ArcFaceDemo#37]
楼主你好，我下载了你的demo，编译完报这个错误，请问有什么好的解决方案嘛，'facedetection.jar这个文件好像转换失败了，我的studio也是3.0的 
Error:Could not resolve all files for configuration ':ArcFaceDemo-master:debugCompileClasspath'.
> Failed to transform file 'facedetection.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file D:\project\ArcFaceDemo\ArcFaceDemo-master\libs\facedetection.jar does not exist.
> Failed to transform file 'facerecognition.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file D:\project\ArcFaceDemo\ArcFaceDemo-master\libs\facerecognition.jar does not exist.
> Failed to transform file 'facetracking.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file D:\project\ArcFaceDemo\ArcFaceDemo-master\libs\facetracking.jar does not exist.
> Failed to transform file 'ageestimation.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file D:\project\ArcFaceDemo\ArcFaceDemo-master\libs\ageestimation.jar does not exist.
> Failed to transform file 'genderestimation.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file D:\project\ArcFaceDemo\ArcFaceDemo-master\libs\genderestimation.jar does not exist.

**Comment by gqjjqg** [comment]
请仔细阅读log，是缺少jar。 解决办法，按照readme步骤操作。 在2018年01月10日 11:35 ，cpq0329写道： 楼主你好，我下载了你的demo，编译完报这个错误，请问有什么好的解决方案嘛，'facedetection.jar这个文件好像转换失败了，我的studio也是3.0的 Error:Could not resolve all files for configuration ':ArcFaceDemo-master:debugCompileClasspath'. Failed to transform file 'facedetection.jar' to match attributes {artifactType=android-classes} using transform JarTransform Transform output file D:\project\ArcFaceDemo\ArcFaceDemo-master\libs\facedetection.jar does not exist. Failed to transform file 'facerecognition.jar' to match attributes {artifactType=android-classes} using transform JarTransform Transform output file D:\project\ArcFaceDemo\ArcFaceDemo-master\libs\facerecognition.jar does not exist. Failed to transform file 'facetracking.jar' to match attributes {artifactType=android-classes} using transform JarTransform Transform output file D:\project\ArcFaceDemo\ArcFaceDemo-master\libs\facetracking.jar does not exist. Failed to transform file 'ageestimation.jar' to match attributes {artifactType=android-classes} using transform JarTransform Transform output file D:\project\ArcFaceDemo\ArcFaceDemo-master\libs\ageestimation.jar does not exist. Failed to transform file 'genderestimation.jar' to match attributes {artifactType=android-classes} using transform JarTransform Transform output file D:\project\ArcFaceDemo\ArcFaceDemo-master\libs\genderestimation.jar does not exist. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cpq0329** [comment]
嗯。。可以运行了 。。但是拍照或者选择照片会提示  “FD初始化失败，错误码：28673” 想问下这个是不是因为楼主注册的那些key过期了 这个检测的SDK是有免费试用期还是怎样？

**Comment by cpq0329** [comment]
@gqjjqg 你好 请问你有遇到这个问题吗。 拍照或者选择照片会提示 “FD初始化失败，错误码：28673”

**Comment by gqjjqg** [comment]
请对照错误码表，一般情况都是没按照readme操作 在2018年01月10日 17:17 ，cpq0329写道： @gqjjqg 你好 请问你有遇到这个问题吗。 拍照或者选择照片会提示 “FD初始化失败，错误码：28673” — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by gqjjqg** [comment]
demo里不含私人申请的sdk，要用demo需要自己申请，具体步骤参考readme 在2018年01月10日 16:25 ，cpq0329写道： 嗯。。可以运行了 。。但是拍照或者选择照片会提示 “FD初始化失败，错误码：28673” 想问下这个是不是因为楼主注册的那些key过期了 这个检测的SDK是有免费试用期还是怎样？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
